# Generated by Django 5.0.4 on 2026-04-25 23:08

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Material',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(max_length=100)),
                ('stock', models.FloatField(default=0)),
                ('min_stock', models.FloatField(default=0)),
                ('unit', models.CharField(max_length=50)),
                ('last_entry', models.DateField(auto_now=True)),
            ],
        ),
    ]
