# Generated by Django 5.0.4 on 2026-04-26 23:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='material',
            name='max_stock',
            field=models.FloatField(default=1000),
        ),
    ]
