# Generated by Django 5.0.4 on 2026-05-29 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventario', '0004_movement'),
        ('pedido', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='cantidad_usada',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='fecha_inicio',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='material_usado',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='production_orders', to='inventario.material'),
        ),
        migrations.AddField(
            model_name='order',
            name='observaciones_produccion',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='order',
            name='operario',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
