# Generated by Django 5.0.4 on 2026-05-31 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pedido', '0002_order_cantidad_usada_order_fecha_inicio_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='size',
            field=models.IntegerField(default=35),
        ),
    ]
